name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: |
        cd Financial.Microservices
        dotnet restore
    - name: Build
      run: |
        cd Financial.Microservices
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd Financial.Microservices
        dotnet test --no-restore --verbosity normal
