name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd Financial.Microservices
        dotnet restore
    - name: Build
      run: |
        cd Financial.Microservices
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd Financial.Microservices
        dotnet test --no-restore --verbosity normal
