name: Sonar-Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: sonarscan-dotnet
      # You may pin to the exact commit or the version.
      # uses: highbyte/sonarscan-dotnet@90025f8a91fb480278dbd6cf740ee9d862f7794c
      uses: highbyte/sonarscan-dotnet@v2.1.1-beta
      with:
        # The key of the SonarQube project
        sonarProjectKey: sp9usb_financial-microservices
        # The name of the SonarQube project
        sonarProjectName: financial-microservices
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: sp9usb
        # Optional command arguments to 'dotnet build'
        dotnetBuildArguments: ./Financial.Microservices
        # Optional command arguments to 'dotnet test'
        dotnetTestArguments: ./Financial.Microservices
        # Optional. Set to 1 or true to not run 'dotnet test' command
        dotnetDisableTests: # optional
        # Optional extra command arguments the the SonarScanner 'begin' command
        sonarBeginArguments: # optional
        # The SonarQube server URL. For SonarCloud, skip this setting.
        sonarHostname: https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
